
project_id = "etrxjxstjfcozdjumfsj"

[functions.create-dev-admin]
verify_jwt = false

[functions.coresignal-person-enrichment]
verify_jwt = true

[functions.set-current-organization]
verify_jwt = true

[functions.parse-resume]
verify_jwt = true

[functions.public-submit-application]
verify_jwt = false
