project_id = "etrxjxstjfcozdjumfsj"

[functions.create-dev-admin]
verify_jwt = false

[functions.download-attachment]
verify_jwt = true

[functions.upload-invoice-document]
verify_jwt = true

[functions.upload-platform-asset]
verify_jwt = true

[functions.set-current-organization]
verify_jwt = true

[functions.parse-resume]
verify_jwt = true

[functions.public-submit-application]
verify_jwt = false

[functions.convert-document-to-pdf]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false