export interface LocationOption {
  value: string // Unique identifier: "city,state,country" or "state,country" or "country"
  label: string // Display label: "City, State, Country" or "State, Country" or "Country"
  city?: string
  state?: string
  country: string
  countryCode: string
  type: 'city' | 'state' | 'country'
}

export const LOCATION_OPTIONS: LocationOption[] = [
  // United States - Major Cities
  { value: "New York,NY,US", label: "New York, NY, United States", city: "New York", state: "NY", country: "United States", countryCode: "US", type: "city" },
  { value: "Los Angeles,CA,US", label: "Los Angeles, CA, United States", city: "Los Angeles", state: "CA", country: "United States", countryCode: "US", type: "city" },
  { value: "Chicago,IL,US", label: "Chicago, IL, United States", city: "Chicago", state: "IL", country: "United States", countryCode: "US", type: "city" },
  { value: "Houston,TX,US", label: "Houston, TX, United States", city: "Houston", state: "TX", country: "United States", countryCode: "US", type: "city" },
  { value: "Phoenix,AZ,US", label: "Phoenix, AZ, United States", city: "Phoenix", state: "AZ", country: "United States", countryCode: "US", type: "city" },
  { value: "Philadelphia,PA,US", label: "Philadelphia, PA, United States", city: "Philadelphia", state: "PA", country: "United States", countryCode: "US", type: "city" },
  { value: "San Antonio,TX,US", label: "San Antonio, TX, United States", city: "San Antonio", state: "TX", country: "United States", countryCode: "US", type: "city" },
  { value: "San Diego,CA,US", label: "San Diego, CA, United States", city: "San Diego", state: "CA", country: "United States", countryCode: "US", type: "city" },
  { value: "Dallas,TX,US", label: "Dallas, TX, United States", city: "Dallas", state: "TX", country: "United States", countryCode: "US", type: "city" },
  { value: "San Jose,CA,US", label: "San Jose, CA, United States", city: "San Jose", state: "CA", country: "United States", countryCode: "US", type: "city" },
  { value: "Austin,TX,US", label: "Austin, TX, United States", city: "Austin", state: "TX", country: "United States", countryCode: "US", type: "city" },
  { value: "Jacksonville,FL,US", label: "Jacksonville, FL, United States", city: "Jacksonville", state: "FL", country: "United States", countryCode: "US", type: "city" },
  { value: "San Francisco,CA,US", label: "San Francisco, CA, United States", city: "San Francisco", state: "CA", country: "United States", countryCode: "US", type: "city" },
  { value: "Columbus,OH,US", label: "Columbus, OH, United States", city: "Columbus", state: "OH", country: "United States", countryCode: "US", type: "city" },
  { value: "Indianapolis,IN,US", label: "Indianapolis, IN, United States", city: "Indianapolis", state: "IN", country: "United States", countryCode: "US", type: "city" },
  { value: "Seattle,WA,US", label: "Seattle, WA, United States", city: "Seattle", state: "WA", country: "United States", countryCode: "US", type: "city" },
  { value: "Denver,CO,US", label: "Denver, CO, United States", city: "Denver", state: "CO", country: "United States", countryCode: "US", type: "city" },
  { value: "Washington,DC,US", label: "Washington, DC, United States", city: "Washington", state: "DC", country: "United States", countryCode: "US", type: "city" },
  { value: "Boston,MA,US", label: "Boston, MA, United States", city: "Boston", state: "MA", country: "United States", countryCode: "US", type: "city" },
  { value: "Nashville,TN,US", label: "Nashville, TN, United States", city: "Nashville", state: "TN", country: "United States", countryCode: "US", type: "city" },
  { value: "Detroit,MI,US", label: "Detroit, MI, United States", city: "Detroit", state: "MI", country: "United States", countryCode: "US", type: "city" },
  { value: "Portland,OR,US", label: "Portland, OR, United States", city: "Portland", state: "OR", country: "United States", countryCode: "US", type: "city" },
  { value: "Las Vegas,NV,US", label: "Las Vegas, NV, United States", city: "Las Vegas", state: "NV", country: "United States", countryCode: "US", type: "city" },
  { value: "Miami,FL,US", label: "Miami, FL, United States", city: "Miami", state: "FL", country: "United States", countryCode: "US", type: "city" },
  { value: "Atlanta,GA,US", label: "Atlanta, GA, United States", city: "Atlanta", state: "GA", country: "United States", countryCode: "US", type: "city" },
  { value: "Minneapolis,MN,US", label: "Minneapolis, MN, United States", city: "Minneapolis", state: "MN", country: "United States", countryCode: "US", type: "city" },
  { value: "Charlotte,NC,US", label: "Charlotte, NC, United States", city: "Charlotte", state: "NC", country: "United States", countryCode: "US", type: "city" },
  { value: "Raleigh,NC,US", label: "Raleigh, NC, United States", city: "Raleigh", state: "NC", country: "United States", countryCode: "US", type: "city" },
  { value: "Tampa,FL,US", label: "Tampa, FL, United States", city: "Tampa", state: "FL", country: "United States", countryCode: "US", type: "city" },
  { value: "Orlando,FL,US", label: "Orlando, FL, United States", city: "Orlando", state: "FL", country: "United States", countryCode: "US", type: "city" },

  // US States
  { value: "AL,US", label: "Alabama, United States", state: "AL", country: "United States", countryCode: "US", type: "state" },
  { value: "AK,US", label: "Alaska, United States", state: "AK", country: "United States", countryCode: "US", type: "state" },
  { value: "AZ,US", label: "Arizona, United States", state: "AZ", country: "United States", countryCode: "US", type: "state" },
  { value: "AR,US", label: "Arkansas, United States", state: "AR", country: "United States", countryCode: "US", type: "state" },
  { value: "CA,US", label: "California, United States", state: "CA", country: "United States", countryCode: "US", type: "state" },
  { value: "CO,US", label: "Colorado, United States", state: "CO", country: "United States", countryCode: "US", type: "state" },
  { value: "CT,US", label: "Connecticut, United States", state: "CT", country: "United States", countryCode: "US", type: "state" },
  { value: "DE,US", label: "Delaware, United States", state: "DE", country: "United States", countryCode: "US", type: "state" },
  { value: "FL,US", label: "Florida, United States", state: "FL", country: "United States", countryCode: "US", type: "state" },
  { value: "GA,US", label: "Georgia, United States", state: "GA", country: "United States", countryCode: "US", type: "state" },
  { value: "HI,US", label: "Hawaii, United States", state: "HI", country: "United States", countryCode: "US", type: "state" },
  { value: "ID,US", label: "Idaho, United States", state: "ID", country: "United States", countryCode: "US", type: "state" },
  { value: "IL,US", label: "Illinois, United States", state: "IL", country: "United States", countryCode: "US", type: "state" },
  { value: "IN,US", label: "Indiana, United States", state: "IN", country: "United States", countryCode: "US", type: "state" },
  { value: "IA,US", label: "Iowa, United States", state: "IA", country: "United States", countryCode: "US", type: "state" },
  { value: "KS,US", label: "Kansas, United States", state: "KS", country: "United States", countryCode: "US", type: "state" },
  { value: "KY,US", label: "Kentucky, United States", state: "KY", country: "United States", countryCode: "US", type: "state" },
  { value: "LA,US", label: "Louisiana, United States", state: "LA", country: "United States", countryCode: "US", type: "state" },
  { value: "ME,US", label: "Maine, United States", state: "ME", country: "United States", countryCode: "US", type: "state" },
  { value: "MD,US", label: "Maryland, United States", state: "MD", country: "United States", countryCode: "US", type: "state" },
  { value: "MA,US", label: "Massachusetts, United States", state: "MA", country: "United States", countryCode: "US", type: "state" },
  { value: "MI,US", label: "Michigan, United States", state: "MI", country: "United States", countryCode: "US", type: "state" },
  { value: "MN,US", label: "Minnesota, United States", state: "MN", country: "United States", countryCode: "US", type: "state" },
  { value: "MS,US", label: "Mississippi, United States", state: "MS", country: "United States", countryCode: "US", type: "state" },
  { value: "MO,US", label: "Missouri, United States", state: "MO", country: "United States", countryCode: "US", type: "state" },
  { value: "MT,US", label: "Montana, United States", state: "MT", country: "United States", countryCode: "US", type: "state" },
  { value: "NE,US", label: "Nebraska, United States", state: "NE", country: "United States", countryCode: "US", type: "state" },
  { value: "NV,US", label: "Nevada, United States", state: "NV", country: "United States", countryCode: "US", type: "state" },
  { value: "NH,US", label: "New Hampshire, United States", state: "NH", country: "United States", countryCode: "US", type: "state" },
  { value: "NJ,US", label: "New Jersey, United States", state: "NJ", country: "United States", countryCode: "US", type: "state" },
  { value: "NM,US", label: "New Mexico, United States", state: "NM", country: "United States", countryCode: "US", type: "state" },
  { value: "NY,US", label: "New York, United States", state: "NY", country: "United States", countryCode: "US", type: "state" },
  { value: "NC,US", label: "North Carolina, United States", state: "NC", country: "United States", countryCode: "US", type: "state" },
  { value: "ND,US", label: "North Dakota, United States", state: "ND", country: "United States", countryCode: "US", type: "state" },
  { value: "OH,US", label: "Ohio, United States", state: "OH", country: "United States", countryCode: "US", type: "state" },
  { value: "OK,US", label: "Oklahoma, United States", state: "OK", country: "United States", countryCode: "US", type: "state" },
  { value: "OR,US", label: "Oregon, United States", state: "OR", country: "United States", countryCode: "US", type: "state" },
  { value: "PA,US", label: "Pennsylvania, United States", state: "PA", country: "United States", countryCode: "US", type: "state" },
  { value: "RI,US", label: "Rhode Island, United States", state: "RI", country: "United States", countryCode: "US", type: "state" },
  { value: "SC,US", label: "South Carolina, United States", state: "SC", country: "United States", countryCode: "US", type: "state" },
  { value: "SD,US", label: "South Dakota, United States", state: "SD", country: "United States", countryCode: "US", type: "state" },
  { value: "TN,US", label: "Tennessee, United States", state: "TN", country: "United States", countryCode: "US", type: "state" },
  { value: "TX,US", label: "Texas, United States", state: "TX", country: "United States", countryCode: "US", type: "state" },
  { value: "UT,US", label: "Utah, United States", state: "UT", country: "United States", countryCode: "US", type: "state" },
  { value: "VT,US", label: "Vermont, United States", state: "VT", country: "United States", countryCode: "US", type: "state" },
  { value: "VA,US", label: "Virginia, United States", state: "VA", country: "United States", countryCode: "US", type: "state" },
  { value: "WA,US", label: "Washington, United States", state: "WA", country: "United States", countryCode: "US", type: "state" },
  { value: "WV,US", label: "West Virginia, United States", state: "WV", country: "United States", countryCode: "US", type: "state" },
  { value: "WI,US", label: "Wisconsin, United States", state: "WI", country: "United States", countryCode: "US", type: "state" },
  { value: "WY,US", label: "Wyoming, United States", state: "WY", country: "United States", countryCode: "US", type: "state" },
  { value: "DC,US", label: "District of Columbia, United States", state: "DC", country: "United States", countryCode: "US", type: "state" },

  // Canada - Major Cities
  { value: "Toronto,ON,CA", label: "Toronto, ON, Canada", city: "Toronto", state: "ON", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Montreal,QC,CA", label: "Montreal, QC, Canada", city: "Montreal", state: "QC", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Vancouver,BC,CA", label: "Vancouver, BC, Canada", city: "Vancouver", state: "BC", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Calgary,AB,CA", label: "Calgary, AB, Canada", city: "Calgary", state: "AB", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Edmonton,AB,CA", label: "Edmonton, AB, Canada", city: "Edmonton", state: "AB", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Ottawa,ON,CA", label: "Ottawa, ON, Canada", city: "Ottawa", state: "ON", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Winnipeg,MB,CA", label: "Winnipeg, MB, Canada", city: "Winnipeg", state: "MB", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Quebec City,QC,CA", label: "Quebec City, QC, Canada", city: "Quebec City", state: "QC", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Hamilton,ON,CA", label: "Hamilton, ON, Canada", city: "Hamilton", state: "ON", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Kitchener,ON,CA", label: "Kitchener, ON, Canada", city: "Kitchener", state: "ON", country: "Canada", countryCode: "CA", type: "city" },

  // Canada Provinces
  { value: "AB,CA", label: "Alberta, Canada", state: "AB", country: "Canada", countryCode: "CA", type: "state" },
  { value: "BC,CA", label: "British Columbia, Canada", state: "BC", country: "Canada", countryCode: "CA", type: "state" },
  { value: "MB,CA", label: "Manitoba, Canada", state: "MB", country: "Canada", countryCode: "CA", type: "state" },
  { value: "NB,CA", label: "New Brunswick, Canada", state: "NB", country: "Canada", countryCode: "CA", type: "state" },
  { value: "NL,CA", label: "Newfoundland and Labrador, Canada", state: "NL", country: "Canada", countryCode: "CA", type: "state" },
  { value: "NS,CA", label: "Nova Scotia, Canada", state: "NS", country: "Canada", countryCode: "CA", type: "state" },
  { value: "ON,CA", label: "Ontario, Canada", state: "ON", country: "Canada", countryCode: "CA", type: "state" },
  { value: "PE,CA", label: "Prince Edward Island, Canada", state: "PE", country: "Canada", countryCode: "CA", type: "state" },
  { value: "QC,CA", label: "Quebec, Canada", state: "QC", country: "Canada", countryCode: "CA", type: "state" },
  { value: "SK,CA", label: "Saskatchewan, Canada", state: "SK", country: "Canada", countryCode: "CA", type: "state" },
  { value: "NT,CA", label: "Northwest Territories, Canada", state: "NT", country: "Canada", countryCode: "CA", type: "state" },
  { value: "NU,CA", label: "Nunavut, Canada", state: "NU", country: "Canada", countryCode: "CA", type: "state" },
  { value: "YT,CA", label: "Yukon, Canada", state: "YT", country: "Canada", countryCode: "CA", type: "state" },

  // Mexico - Major Cities
  { value: "Mexico City,CDMX,MX", label: "Mexico City, CDMX, Mexico", city: "Mexico City", state: "CDMX", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Guadalajara,JAL,MX", label: "Guadalajara, JAL, Mexico", city: "Guadalajara", state: "JAL", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Monterrey,NLE,MX", label: "Monterrey, NLE, Mexico", city: "Monterrey", state: "NLE", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Puebla,PUE,MX", label: "Puebla, PUE, Mexico", city: "Puebla", state: "PUE", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Tijuana,BCN,MX", label: "Tijuana, BCN, Mexico", city: "Tijuana", state: "BCN", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "León,GTO,MX", label: "León, GTO, Mexico", city: "León", state: "GTO", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Juárez,CHH,MX", label: "Juárez, CHH, Mexico", city: "Juárez", state: "CHH", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Zapopan,JAL,MX", label: "Zapopan, JAL, Mexico", city: "Zapopan", state: "JAL", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Cancún,ROO,MX", label: "Cancún, ROO, Mexico", city: "Cancún", state: "ROO", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Mérida,YUC,MX", label: "Mérida, YUC, Mexico", city: "Mérida", state: "YUC", country: "Mexico", countryCode: "MX", type: "city" },

  // Mexico States
  { value: "AGS,MX", label: "Aguascalientes, Mexico", state: "AGS", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "BCN,MX", label: "Baja California, Mexico", state: "BCN", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "BCS,MX", label: "Baja California Sur, Mexico", state: "BCS", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "CAM,MX", label: "Campeche, Mexico", state: "CAM", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "CHP,MX", label: "Chiapas, Mexico", state: "CHP", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "CHH,MX", label: "Chihuahua, Mexico", state: "CHH", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "CDMX,MX", label: "Mexico City, Mexico", state: "CDMX", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "COA,MX", label: "Coahuila, Mexico", state: "COA", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "COL,MX", label: "Colima, Mexico", state: "COL", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "DUR,MX", label: "Durango, Mexico", state: "DUR", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "GTO,MX", label: "Guanajuato, Mexico", state: "GTO", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "GRO,MX", label: "Guerrero, Mexico", state: "GRO", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "HID,MX", label: "Hidalgo, Mexico", state: "HID", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "JAL,MX", label: "Jalisco, Mexico", state: "JAL", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "MEX,MX", label: "State of Mexico, Mexico", state: "MEX", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "MIC,MX", label: "Michoacán, Mexico", state: "MIC", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "MOR,MX", label: "Morelos, Mexico", state: "MOR", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "NAY,MX", label: "Nayarit, Mexico", state: "NAY", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "NLE,MX", label: "Nuevo León, Mexico", state: "NLE", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "OAX,MX", label: "Oaxaca, Mexico", state: "OAX", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "PUE,MX", label: "Puebla, Mexico", state: "PUE", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "QRO,MX", label: "Querétaro, Mexico", state: "QRO", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "ROO,MX", label: "Quintana Roo, Mexico", state: "ROO", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "SLP,MX", label: "San Luis Potosí, Mexico", state: "SLP", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "SIN,MX", label: "Sinaloa, Mexico", state: "SIN", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "SON,MX", label: "Sonora, Mexico", state: "SON", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "TAB,MX", label: "Tabasco, Mexico", state: "TAB", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "TAM,MX", label: "Tamaulipas, Mexico", state: "TAM", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "TLA,MX", label: "Tlaxcala, Mexico", state: "TLA", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "VER,MX", label: "Veracruz, Mexico", state: "VER", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "YUC,MX", label: "Yucatán, Mexico", state: "YUC", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "ZAC,MX", label: "Zacatecas, Mexico", state: "ZAC", country: "Mexico", countryCode: "MX", type: "state" },

  // Colombia - Major Cities
  { value: "Bogotá,DC,CO", label: "Bogotá, DC, Colombia", city: "Bogotá", state: "DC", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Medellín,ANT,CO", label: "Medellín, ANT, Colombia", city: "Medellín", state: "ANT", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Cali,VAC,CO", label: "Cali, VAC, Colombia", city: "Cali", state: "VAC", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Barranquilla,ATL,CO", label: "Barranquilla, ATL, Colombia", city: "Barranquilla", state: "ATL", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Cartagena,BOL,CO", label: "Cartagena, BOL, Colombia", city: "Cartagena", state: "BOL", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Cúcuta,NSA,CO", label: "Cúcuta, NSA, Colombia", city: "Cúcuta", state: "NSA", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Bucaramanga,SAN,CO", label: "Bucaramanga, SAN, Colombia", city: "Bucaramanga", state: "SAN", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Pereira,RIS,CO", label: "Pereira, RIS, Colombia", city: "Pereira", state: "RIS", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Santa Marta,MAG,CO", label: "Santa Marta, MAG, Colombia", city: "Santa Marta", state: "MAG", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Ibagué,TOL,CO", label: "Ibagué, TOL, Colombia", city: "Ibagué", state: "TOL", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Manizales,CAL,CO", label: "Manizales, CAL, Colombia", city: "Manizales", state: "CAL", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Villavicencio,MET,CO", label: "Villavicencio, MET, Colombia", city: "Villavicencio", state: "MET", country: "Colombia", countryCode: "CO", type: "city" },

  // Colombia Departments
  { value: "AMA,CO", label: "Amazonas, Colombia", state: "AMA", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "ANT,CO", label: "Antioquia, Colombia", state: "ANT", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "ARA,CO", label: "Arauca, Colombia", state: "ARA", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "ATL,CO", label: "Atlántico, Colombia", state: "ATL", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "BOL,CO", label: "Bolívar, Colombia", state: "BOL", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "BOY,CO", label: "Boyacá, Colombia", state: "BOY", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "CAL,CO", label: "Caldas, Colombia", state: "CAL", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "CAQ,CO", label: "Caquetá, Colombia", state: "CAQ", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "CAS,CO", label: "Casanare, Colombia", state: "CAS", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "CAU,CO", label: "Cauca, Colombia", state: "CAU", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "CES,CO", label: "Cesar, Colombia", state: "CES", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "CHO,CO", label: "Chocó, Colombia", state: "CHO", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "COR,CO", label: "Córdoba, Colombia", state: "COR", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "CUN,CO", label: "Cundinamarca, Colombia", state: "CUN", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "GUA,CO", label: "Guainía, Colombia", state: "GUA", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "GUV,CO", label: "Guaviare, Colombia", state: "GUV", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "HUI,CO", label: "Huila, Colombia", state: "HUI", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "LAG,CO", label: "La Guajira, Colombia", state: "LAG", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "MAG,CO", label: "Magdalena, Colombia", state: "MAG", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "MET,CO", label: "Meta, Colombia", state: "MET", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "NAR,CO", label: "Nariño, Colombia", state: "NAR", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "NSA,CO", label: "Norte de Santander, Colombia", state: "NSA", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "PUT,CO", label: "Putumayo, Colombia", state: "PUT", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "QUI,CO", label: "Quindío, Colombia", state: "QUI", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "RIS,CO", label: "Risaralda, Colombia", state: "RIS", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "SAP,CO", label: "San Andrés y Providencia, Colombia", state: "SAP", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "SAN,CO", label: "Santander, Colombia", state: "SAN", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "SUC,CO", label: "Sucre, Colombia", state: "SUC", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "TOL,CO", label: "Tolima, Colombia", state: "TOL", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "VAC,CO", label: "Valle del Cauca, Colombia", state: "VAC", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "VAU,CO", label: "Vaupés, Colombia", state: "VAU", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "VID,CO", label: "Vichada, Colombia", state: "VID", country: "Colombia", countryCode: "CO", type: "state" },
  { value: "DC,CO", label: "Bogotá D.C., Colombia", state: "DC", country: "Colombia", countryCode: "CO", type: "state" },

  // Argentina - Major Cities
  { value: "Buenos Aires,C,AR", label: "Buenos Aires, C, Argentina", city: "Buenos Aires", state: "C", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "Córdoba,X,AR", label: "Córdoba, X, Argentina", city: "Córdoba", state: "X", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "Rosario,S,AR", label: "Rosario, S, Argentina", city: "Rosario", state: "S", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "Mendoza,M,AR", label: "Mendoza, M, Argentina", city: "Mendoza", state: "M", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "La Plata,B,AR", label: "La Plata, B, Argentina", city: "La Plata", state: "B", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "San Miguel de Tucumán,T,AR", label: "San Miguel de Tucumán, T, Argentina", city: "San Miguel de Tucumán", state: "T", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "Mar del Plata,B,AR", label: "Mar del Plata, B, Argentina", city: "Mar del Plata", state: "B", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "Salta,A,AR", label: "Salta, A, Argentina", city: "Salta", state: "A", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "Santa Fe,S,AR", label: "Santa Fe, S, Argentina", city: "Santa Fe", state: "S", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "San Juan,J,AR", label: "San Juan, J, Argentina", city: "San Juan", state: "J", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "Resistencia,H,AR", label: "Resistencia, H, Argentina", city: "Resistencia", state: "H", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "Neuquén,Q,AR", label: "Neuquén, Q, Argentina", city: "Neuquén", state: "Q", country: "Argentina", countryCode: "AR", type: "city" },

  // Argentina Provinces
  { value: "B,AR", label: "Buenos Aires, Argentina", state: "B", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "K,AR", label: "Catamarca, Argentina", state: "K", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "H,AR", label: "Chaco, Argentina", state: "H", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "U,AR", label: "Chubut, Argentina", state: "U", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "C,AR", label: "Ciudad Autónoma de Buenos Aires, Argentina", state: "C", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "X,AR", label: "Córdoba, Argentina", state: "X", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "W,AR", label: "Corrientes, Argentina", state: "W", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "E,AR", label: "Entre Ríos, Argentina", state: "E", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "P,AR", label: "Formosa, Argentina", state: "P", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "Y,AR", label: "Jujuy, Argentina", state: "Y", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "L,AR", label: "La Pampa, Argentina", state: "L", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "F,AR", label: "La Rioja, Argentina", state: "F", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "M,AR", label: "Mendoza, Argentina", state: "M", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "N,AR", label: "Misiones, Argentina", state: "N", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "Q,AR", label: "Neuquén, Argentina", state: "Q", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "R,AR", label: "Río Negro, Argentina", state: "R", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "A,AR", label: "Salta, Argentina", state: "A", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "J,AR", label: "San Juan, Argentina", state: "J", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "D,AR", label: "San Luis, Argentina", state: "D", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "Z,AR", label: "Santa Cruz, Argentina", state: "Z", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "S,AR", label: "Santa Fe, Argentina", state: "S", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "G,AR", label: "Santiago del Estero, Argentina", state: "G", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "V,AR", label: "Tierra del Fuego, Argentina", state: "V", country: "Argentina", countryCode: "AR", type: "state" },
  { value: "T,AR", label: "Tucumán, Argentina", state: "T", country: "Argentina", countryCode: "AR", type: "state" },

  // Chile - Major Cities
  { value: "Santiago,RM,CL", label: "Santiago, RM, Chile", city: "Santiago", state: "RM", country: "Chile", countryCode: "CL", type: "city" },
  { value: "Valparaíso,VS,CL", label: "Valparaíso, VS, Chile", city: "Valparaíso", state: "VS", country: "Chile", countryCode: "CL", type: "city" },
  { value: "Concepción,BI,CL", label: "Concepción, BI, Chile", city: "Concepción", state: "BI", country: "Chile", countryCode: "CL", type: "city" },
  { value: "La Serena,CO,CL", label: "La Serena, CO, Chile", city: "La Serena", state: "CO", country: "Chile", countryCode: "CL", type: "city" },
  { value: "Antofagasta,AN,CL", label: "Antofagasta, AN, Chile", city: "Antofagasta", state: "AN", country: "Chile", countryCode: "CL", type: "city" },
  { value: "Temuco,AR,CL", label: "Temuco, AR, Chile", city: "Temuco", state: "AR", country: "Chile", countryCode: "CL", type: "city" },
  { value: "Rancagua,LI,CL", label: "Rancagua, LI, Chile", city: "Rancagua", state: "LI", country: "Chile", countryCode: "CL", type: "city" },
  { value: "Talca,ML,CL", label: "Talca, ML, Chile", city: "Talca", state: "ML", country: "Chile", countryCode: "CL", type: "city" },
  { value: "Arica,AP,CL", label: "Arica, AP, Chile", city: "Arica", state: "AP", country: "Chile", countryCode: "CL", type: "city" },
  { value: "Chillán,NB,CL", label: "Chillán, NB, Chile", city: "Chillán", state: "NB", country: "Chile", countryCode: "CL", type: "city" },
  { value: "Puerto Montt,LL,CL", label: "Puerto Montt, LL, Chile", city: "Puerto Montt", state: "LL", country: "Chile", countryCode: "CL", type: "city" },
  { value: "Iquique,TA,CL", label: "Iquique, TA, Chile", city: "Iquique", state: "TA", country: "Chile", countryCode: "CL", type: "city" },

  // Chile Regions
  { value: "AP,CL", label: "Arica y Parinacota, Chile", state: "AP", country: "Chile", countryCode: "CL", type: "state" },
  { value: "TA,CL", label: "Tarapacá, Chile", state: "TA", country: "Chile", countryCode: "CL", type: "state" },
  { value: "AN,CL", label: "Antofagasta, Chile", state: "AN", country: "Chile", countryCode: "CL", type: "state" },
  { value: "AT,CL", label: "Atacama, Chile", state: "AT", country: "Chile", countryCode: "CL", type: "state" },
  { value: "CO,CL", label: "Coquimbo, Chile", state: "CO", country: "Chile", countryCode: "CL", type: "state" },
  { value: "VS,CL", label: "Valparaíso, Chile", state: "VS", country: "Chile", countryCode: "CL", type: "state" },
  { value: "RM,CL", label: "Metropolitana de Santiago, Chile", state: "RM", country: "Chile", countryCode: "CL", type: "state" },
  { value: "LI,CL", label: "O'Higgins, Chile", state: "LI", country: "Chile", countryCode: "CL", type: "state" },
  { value: "ML,CL", label: "Maule, Chile", state: "ML", country: "Chile", countryCode: "CL", type: "state" },
  { value: "NB,CL", label: "Ñuble, Chile", state: "NB", country: "Chile", countryCode: "CL", type: "state" },
  { value: "BI,CL", label: "Biobío, Chile", state: "BI", country: "Chile", countryCode: "CL", type: "state" },
  { value: "AR,CL", label: "Araucanía, Chile", state: "AR", country: "Chile", countryCode: "CL", type: "state" },
  { value: "LR,CL", label: "Los Ríos, Chile", state: "LR", country: "Chile", countryCode: "CL", type: "state" },
  { value: "LL,CL", label: "Los Lagos, Chile", state: "LL", country: "Chile", countryCode: "CL", type: "state" },
  { value: "AI,CL", label: "Aysén, Chile", state: "AI", country: "Chile", countryCode: "CL", type: "state" },
  { value: "MA,CL", label: "Magallanes, Chile", state: "MA", country: "Chile", countryCode: "CL", type: "state" },

  // Countries (for selecting entire country)
  { value: "US", label: "United States", country: "United States", countryCode: "US", type: "country" },
  { value: "CA", label: "Canada", country: "Canada", countryCode: "CA", type: "country" },
  { value: "MX", label: "Mexico", country: "Mexico", countryCode: "MX", type: "country" },
  { value: "CO", label: "Colombia", country: "Colombia", countryCode: "CO", type: "country" },
  { value: "AR", label: "Argentina", country: "Argentina", countryCode: "AR", type: "country" },
  { value: "CL", label: "Chile", country: "Chile", countryCode: "CL", type: "country" },
]
