export interface LocationOption {
  value: string // Unique identifier: "city,state,country" or "state,country" or "country"
  label: string // Display label: "City, State, Country" or "State, Country" or "Country"
  city?: string
  state?: string
  country: string
  countryCode: string
  type: 'city' | 'state' | 'country'
}

export const LOCATION_OPTIONS: LocationOption[] = [
  // United States
  { value: "New York,New York,US", label: "New York, NY, United States", city: "New York", state: "New York", country: "United States", countryCode: "US", type: "city" },
  { value: "Los Angeles,California,US", label: "Los Angeles, CA, United States", city: "Los Angeles", state: "California", country: "United States", countryCode: "US", type: "city" },
  { value: "Chicago,Illinois,US", label: "Chicago, IL, United States", city: "Chicago", state: "Illinois", country: "United States", countryCode: "US", type: "city" },
  { value: "Houston,Texas,US", label: "Houston, TX, United States", city: "Houston", state: "Texas", country: "United States", countryCode: "US", type: "city" },
  { value: "Phoenix,Arizona,US", label: "Phoenix, AZ, United States", city: "Phoenix", state: "Arizona", country: "United States", countryCode: "US", type: "city" },
  { value: "Philadelphia,Pennsylvania,US", label: "Philadelphia, PA, United States", city: "Philadelphia", state: "Pennsylvania", country: "United States", countryCode: "US", type: "city" },
  { value: "San Antonio,Texas,US", label: "San Antonio, TX, United States", city: "San Antonio", state: "Texas", country: "United States", countryCode: "US", type: "city" },
  { value: "San Diego,California,US", label: "San Diego, CA, United States", city: "San Diego", state: "California", country: "United States", countryCode: "US", type: "city" },
  { value: "Dallas,Texas,US", label: "Dallas, TX, United States", city: "Dallas", state: "Texas", country: "United States", countryCode: "US", type: "city" },
  { value: "San Jose,California,US", label: "San Jose, CA, United States", city: "San Jose", state: "California", country: "United States", countryCode: "US", type: "city" },
  { value: "Austin,Texas,US", label: "Austin, TX, United States", city: "Austin", state: "Texas", country: "United States", countryCode: "US", type: "city" },
  { value: "Jacksonville,Florida,US", label: "Jacksonville, FL, United States", city: "Jacksonville", state: "Florida", country: "United States", countryCode: "US", type: "city" },
  { value: "San Francisco,California,US", label: "San Francisco, CA, United States", city: "San Francisco", state: "California", country: "United States", countryCode: "US", type: "city" },
  { value: "Columbus,Ohio,US", label: "Columbus, OH, United States", city: "Columbus", state: "Ohio", country: "United States", countryCode: "US", type: "city" },
  { value: "Indianapolis,Indiana,US", label: "Indianapolis, IN, United States", city: "Indianapolis", state: "Indiana", country: "United States", countryCode: "US", type: "city" },
  { value: "Seattle,Washington,US", label: "Seattle, WA, United States", city: "Seattle", state: "Washington", country: "United States", countryCode: "US", type: "city" },
  { value: "Denver,Colorado,US", label: "Denver, CO, United States", city: "Denver", state: "Colorado", country: "United States", countryCode: "US", type: "city" },
  { value: "Washington,District of Columbia,US", label: "Washington, DC, United States", city: "Washington", state: "District of Columbia", country: "United States", countryCode: "US", type: "city" },
  { value: "Boston,Massachusetts,US", label: "Boston, MA, United States", city: "Boston", state: "Massachusetts", country: "United States", countryCode: "US", type: "city" },
  { value: "Nashville,Tennessee,US", label: "Nashville, TN, United States", city: "Nashville", state: "Tennessee", country: "United States", countryCode: "US", type: "city" },
  { value: "Detroit,Michigan,US", label: "Detroit, MI, United States", city: "Detroit", state: "Michigan", country: "United States", countryCode: "US", type: "city" },
  { value: "Portland,Oregon,US", label: "Portland, OR, United States", city: "Portland", state: "Oregon", country: "United States", countryCode: "US", type: "city" },
  { value: "Las Vegas,Nevada,US", label: "Las Vegas, NV, United States", city: "Las Vegas", state: "Nevada", country: "United States", countryCode: "US", type: "city" },
  { value: "Miami,Florida,US", label: "Miami, FL, United States", city: "Miami", state: "Florida", country: "United States", countryCode: "US", type: "city" },
  { value: "Atlanta,Georgia,US", label: "Atlanta, GA, United States", city: "Atlanta", state: "Georgia", country: "United States", countryCode: "US", type: "city" },
  { value: "Minneapolis,Minnesota,US", label: "Minneapolis, MN, United States", city: "Minneapolis", state: "Minnesota", country: "United States", countryCode: "US", type: "city" },
  { value: "Charlotte,North Carolina,US", label: "Charlotte, NC, United States", city: "Charlotte", state: "North Carolina", country: "United States", countryCode: "US", type: "city" },
  { value: "Raleigh,North Carolina,US", label: "Raleigh, NC, United States", city: "Raleigh", state: "North Carolina", country: "United States", countryCode: "US", type: "city" },
  { value: "Tampa,Florida,US", label: "Tampa, FL, United States", city: "Tampa", state: "Florida", country: "United States", countryCode: "US", type: "city" },
  { value: "Orlando,Florida,US", label: "Orlando, FL, United States", city: "Orlando", state: "Florida", country: "United States", countryCode: "US", type: "city" },

  // US States
  { value: "Alabama,US", label: "Alabama, United States", state: "Alabama", country: "United States", countryCode: "US", type: "state" },
  { value: "Alaska,US", label: "Alaska, United States", state: "Alaska", country: "United States", countryCode: "US", type: "state" },
  { value: "Arizona,US", label: "Arizona, United States", state: "Arizona", country: "United States", countryCode: "US", type: "state" },
  { value: "Arkansas,US", label: "Arkansas, United States", state: "Arkansas", country: "United States", countryCode: "US", type: "state" },
  { value: "California,US", label: "California, United States", state: "California", country: "United States", countryCode: "US", type: "state" },
  { value: "Colorado,US", label: "Colorado, United States", state: "Colorado", country: "United States", countryCode: "US", type: "state" },
  { value: "Connecticut,US", label: "Connecticut, United States", state: "Connecticut", country: "United States", countryCode: "US", type: "state" },
  { value: "Delaware,US", label: "Delaware, United States", state: "Delaware", country: "United States", countryCode: "US", type: "state" },
  { value: "Florida,US", label: "Florida, United States", state: "Florida", country: "United States", countryCode: "US", type: "state" },
  { value: "Georgia,US", label: "Georgia, United States", state: "Georgia", country: "United States", countryCode: "US", type: "state" },
  { value: "Hawaii,US", label: "Hawaii, United States", state: "Hawaii", country: "United States", countryCode: "US", type: "state" },
  { value: "Idaho,US", label: "Idaho, United States", state: "Idaho", country: "United States", countryCode: "US", type: "state" },
  { value: "Illinois,US", label: "Illinois, United States", state: "Illinois", country: "United States", countryCode: "US", type: "state" },
  { value: "Indiana,US", label: "Indiana, United States", state: "Indiana", country: "United States", countryCode: "US", type: "state" },
  { value: "Iowa,US", label: "Iowa, United States", state: "Iowa", country: "United States", countryCode: "US", type: "state" },
  { value: "Kansas,US", label: "Kansas, United States", state: "Kansas", country: "United States", countryCode: "US", type: "state" },
  { value: "Kentucky,US", label: "Kentucky, United States", state: "Kentucky", country: "United States", countryCode: "US", type: "state" },
  { value: "Louisiana,US", label: "Louisiana, United States", state: "Louisiana", country: "United States", countryCode: "US", type: "state" },
  { value: "Maine,US", label: "Maine, United States", state: "Maine", country: "United States", countryCode: "US", type: "state" },
  { value: "Maryland,US", label: "Maryland, United States", state: "Maryland", country: "United States", countryCode: "US", type: "state" },
  { value: "Massachusetts,US", label: "Massachusetts, United States", state: "Massachusetts", country: "United States", countryCode: "US", type: "state" },
  { value: "Michigan,US", label: "Michigan, United States", state: "Michigan", country: "United States", countryCode: "US", type: "state" },
  { value: "Minnesota,US", label: "Minnesota, United States", state: "Minnesota", country: "United States", countryCode: "US", type: "state" },
  { value: "Mississippi,US", label: "Mississippi, United States", state: "Mississippi", country: "United States", countryCode: "US", type: "state" },
  { value: "Missouri,US", label: "Missouri, United States", state: "Missouri", country: "United States", countryCode: "US", type: "state" },
  { value: "Montana,US", label: "Montana, United States", state: "Montana", country: "United States", countryCode: "US", type: "state" },
  { value: "Nebraska,US", label: "Nebraska, United States", state: "Nebraska", country: "United States", countryCode: "US", type: "state" },
  { value: "Nevada,US", label: "Nevada, United States", state: "Nevada", country: "United States", countryCode: "US", type: "state" },
  { value: "New Hampshire,US", label: "New Hampshire, United States", state: "New Hampshire", country: "United States", countryCode: "US", type: "state" },
  { value: "New Jersey,US", label: "New Jersey, United States", state: "New Jersey", country: "United States", countryCode: "US", type: "state" },
  { value: "New Mexico,US", label: "New Mexico, United States", state: "New Mexico", country: "United States", countryCode: "US", type: "state" },
  { value: "New York,US", label: "New York, United States", state: "New York", country: "United States", countryCode: "US", type: "state" },
  { value: "North Carolina,US", label: "North Carolina, United States", state: "North Carolina", country: "United States", countryCode: "US", type: "state" },
  { value: "North Dakota,US", label: "North Dakota, United States", state: "North Dakota", country: "United States", countryCode: "US", type: "state" },
  { value: "Ohio,US", label: "Ohio, United States", state: "Ohio", country: "United States", countryCode: "US", type: "state" },
  { value: "Oklahoma,US", label: "Oklahoma, United States", state: "Oklahoma", country: "United States", countryCode: "US", type: "state" },
  { value: "Oregon,US", label: "Oregon, United States", state: "Oregon", country: "United States", countryCode: "US", type: "state" },
  { value: "Pennsylvania,US", label: "Pennsylvania, United States", state: "Pennsylvania", country: "United States", countryCode: "US", type: "state" },
  { value: "Rhode Island,US", label: "Rhode Island, United States", state: "Rhode Island", country: "United States", countryCode: "US", type: "state" },
  { value: "South Carolina,US", label: "South Carolina, United States", state: "South Carolina", country: "United States", countryCode: "US", type: "state" },
  { value: "South Dakota,US", label: "South Dakota, United States", state: "South Dakota", country: "United States", countryCode: "US", type: "state" },
  { value: "Tennessee,US", label: "Tennessee, United States", state: "Tennessee", country: "United States", countryCode: "US", type: "state" },
  { value: "Texas,US", label: "Texas, United States", state: "Texas", country: "United States", countryCode: "US", type: "state" },
  { value: "Utah,US", label: "Utah, United States", state: "Utah", country: "United States", countryCode: "US", type: "state" },
  { value: "Vermont,US", label: "Vermont, United States", state: "Vermont", country: "United States", countryCode: "US", type: "state" },
  { value: "Virginia,US", label: "Virginia, United States", state: "Virginia", country: "United States", countryCode: "US", type: "state" },
  { value: "Washington,US", label: "Washington, United States", state: "Washington", country: "United States", countryCode: "US", type: "state" },
  { value: "West Virginia,US", label: "West Virginia, United States", state: "West Virginia", country: "United States", countryCode: "US", type: "state" },
  { value: "Wisconsin,US", label: "Wisconsin, United States", state: "Wisconsin", country: "United States", countryCode: "US", type: "state" },
  { value: "Wyoming,US", label: "Wyoming, United States", state: "Wyoming", country: "United States", countryCode: "US", type: "state" },
  { value: "District of Columbia,US", label: "District of Columbia, United States", state: "District of Columbia", country: "United States", countryCode: "US", type: "state" },

  // Canada
  { value: "Toronto,Ontario,CA", label: "Toronto, ON, Canada", city: "Toronto", state: "Ontario", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Montreal,Quebec,CA", label: "Montreal, QC, Canada", city: "Montreal", state: "Quebec", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Vancouver,British Columbia,CA", label: "Vancouver, BC, Canada", city: "Vancouver", state: "British Columbia", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Calgary,Alberta,CA", label: "Calgary, AB, Canada", city: "Calgary", state: "Alberta", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Edmonton,Alberta,CA", label: "Edmonton, AB, Canada", city: "Edmonton", state: "Alberta", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Ottawa,Ontario,CA", label: "Ottawa, ON, Canada", city: "Ottawa", state: "Ontario", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Winnipeg,Manitoba,CA", label: "Winnipeg, MB, Canada", city: "Winnipeg", state: "Manitoba", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Quebec City,Quebec,CA", label: "Quebec City, QC, Canada", city: "Quebec City", state: "Quebec", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Hamilton,Ontario,CA", label: "Hamilton, ON, Canada", city: "Hamilton", state: "Ontario", country: "Canada", countryCode: "CA", type: "city" },
  { value: "Kitchener,Ontario,CA", label: "Kitchener, ON, Canada", city: "Kitchener", state: "Ontario", country: "Canada", countryCode: "CA", type: "city" },

  // Canadian Provinces
  { value: "Alberta,CA", label: "Alberta, Canada", state: "Alberta", country: "Canada", countryCode: "CA", type: "state" },
  { value: "British Columbia,CA", label: "British Columbia, Canada", state: "British Columbia", country: "Canada", countryCode: "CA", type: "state" },
  { value: "Manitoba,CA", label: "Manitoba, Canada", state: "Manitoba", country: "Canada", countryCode: "CA", type: "state" },
  { value: "New Brunswick,CA", label: "New Brunswick, Canada", state: "New Brunswick", country: "Canada", countryCode: "CA", type: "state" },
  { value: "Newfoundland and Labrador,CA", label: "Newfoundland and Labrador, Canada", state: "Newfoundland and Labrador", country: "Canada", countryCode: "CA", type: "state" },
  { value: "Nova Scotia,CA", label: "Nova Scotia, Canada", state: "Nova Scotia", country: "Canada", countryCode: "CA", type: "state" },
  { value: "Ontario,CA", label: "Ontario, Canada", state: "Ontario", country: "Canada", countryCode: "CA", type: "state" },
  { value: "Prince Edward Island,CA", label: "Prince Edward Island, Canada", state: "Prince Edward Island", country: "Canada", countryCode: "CA", type: "state" },
  { value: "Quebec,CA", label: "Quebec, Canada", state: "Quebec", country: "Canada", countryCode: "CA", type: "state" },
  { value: "Saskatchewan,CA", label: "Saskatchewan, Canada", state: "Saskatchewan", country: "Canada", countryCode: "CA", type: "state" },
  { value: "Northwest Territories,CA", label: "Northwest Territories, Canada", state: "Northwest Territories", country: "Canada", countryCode: "CA", type: "state" },
  { value: "Nunavut,CA", label: "Nunavut, Canada", state: "Nunavut", country: "Canada", countryCode: "CA", type: "state" },
  { value: "Yukon,CA", label: "Yukon, Canada", state: "Yukon", country: "Canada", countryCode: "CA", type: "state" },

  // Mexico
  { value: "Mexico City,Mexico City,MX", label: "Mexico City, CDMX, Mexico", city: "Mexico City", state: "Mexico City", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Guadalajara,Jalisco,MX", label: "Guadalajara, JAL, Mexico", city: "Guadalajara", state: "Jalisco", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Monterrey,Nuevo León,MX", label: "Monterrey, NLE, Mexico", city: "Monterrey", state: "Nuevo León", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Puebla,Puebla,MX", label: "Puebla, PUE, Mexico", city: "Puebla", state: "Puebla", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Tijuana,Baja California,MX", label: "Tijuana, BCN, Mexico", city: "Tijuana", state: "Baja California", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "León,Guanajuato,MX", label: "León, GTO, Mexico", city: "León", state: "Guanajuato", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Juárez,Chihuahua,MX", label: "Juárez, CHH, Mexico", city: "Juárez", state: "Chihuahua", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Zapopan,Jalisco,MX", label: "Zapopan, JAL, Mexico", city: "Zapopan", state: "Jalisco", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Cancún,Quintana Roo,MX", label: "Cancún, ROO, Mexico", city: "Cancún", state: "Quintana Roo", country: "Mexico", countryCode: "MX", type: "city" },
  { value: "Mérida,Yucatán,MX", label: "Mérida, YUC, Mexico", city: "Mérida", state: "Yucatán", country: "Mexico", countryCode: "MX", type: "city" },

  // Mexican States
  { value: "Aguascalientes,MX", label: "Aguascalientes, Mexico", state: "Aguascalientes", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Baja California,MX", label: "Baja California, Mexico", state: "Baja California", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Baja California Sur,MX", label: "Baja California Sur, Mexico", state: "Baja California Sur", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Campeche,MX", label: "Campeche, Mexico", state: "Campeche", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Chiapas,MX", label: "Chiapas, Mexico", state: "Chiapas", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Chihuahua,MX", label: "Chihuahua, Mexico", state: "Chihuahua", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Mexico City,MX", label: "Mexico City, Mexico", state: "Mexico City", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Coahuila,MX", label: "Coahuila, Mexico", state: "Coahuila", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Colima,MX", label: "Colima, Mexico", state: "Colima", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Durango,MX", label: "Durango, Mexico", state: "Durango", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Guanajuato,MX", label: "Guanajuato, Mexico", state: "Guanajuato", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Guerrero,MX", label: "Guerrero, Mexico", state: "Guerrero", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Hidalgo,MX", label: "Hidalgo, Mexico", state: "Hidalgo", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Jalisco,MX", label: "Jalisco, Mexico", state: "Jalisco", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "State of Mexico,MX", label: "State of Mexico, Mexico", state: "State of Mexico", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Michoacán,MX", label: "Michoacán, Mexico", state: "Michoacán", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Morelos,MX", label: "Morelos, Mexico", state: "Morelos", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Nayarit,MX", label: "Nayarit, Mexico", state: "Nayarit", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Nuevo León,MX", label: "Nuevo León, Mexico", state: "Nuevo León", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Oaxaca,MX", label: "Oaxaca, Mexico", state: "Oaxaca", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Puebla,MX", label: "Puebla, Mexico", state: "Puebla", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Querétaro,MX", label: "Querétaro, Mexico", state: "Querétaro", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Quintana Roo,MX", label: "Quintana Roo, Mexico", state: "Quintana Roo", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "San Luis Potosí,MX", label: "San Luis Potosí, Mexico", state: "San Luis Potosí", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Sinaloa,MX", label: "Sinaloa, Mexico", state: "Sinaloa", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Sonora,MX", label: "Sonora, Mexico", state: "Sonora", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Tabasco,MX", label: "Tabasco, Mexico", state: "Tabasco", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Tamaulipas,MX", label: "Tamaulipas, Mexico", state: "Tamaulipas", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Tlaxcala,MX", label: "Tlaxcala, Mexico", state: "Tlaxcala", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Veracruz,MX", label: "Veracruz, Mexico", state: "Veracruz", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Yucatán,MX", label: "Yucatán, Mexico", state: "Yucatán", country: "Mexico", countryCode: "MX", type: "state" },
  { value: "Zacatecas,MX", label: "Zacatecas, Mexico", state: "Zacatecas", country: "Mexico", countryCode: "MX", type: "state" },

  // Colombia
  { value: "Bogotá,Cundinamarca,CO", label: "Bogotá, Colombia", city: "Bogotá", state: "Cundinamarca", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Medellín,Antioquia,CO", label: "Medellín, Colombia", city: "Medellín", state: "Antioquia", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Cali,Valle del Cauca,CO", label: "Cali, Colombia", city: "Cali", state: "Valle del Cauca", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "Barranquilla,Atlántico,CO", label: "Barranquilla, Colombia", city: "Barranquilla", state: "Atlántico", country: "Colombia", countryCode: "CO", type: "city" },
  { value: "CO", label: "Colombia", country: "Colombia", countryCode: "CO", type: "country" },

  // Argentina
  { value: "Buenos Aires,Buenos Aires,AR", label: "Buenos Aires, Argentina", city: "Buenos Aires", state: "Buenos Aires", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "Córdoba,Córdoba,AR", label: "Córdoba, Argentina", city: "Córdoba", state: "Córdoba", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "Rosario,Santa Fe,AR", label: "Rosario, Argentina", city: "Rosario", state: "Santa Fe", country: "Argentina", countryCode: "AR", type: "city" },
  { value: "AR", label: "Argentina", country: "Argentina", countryCode: "AR", type: "country" },

  // Chile
  { value: "Santiago,Santiago Metropolitan,CL", label: "Santiago, Chile", city: "Santiago", state: "Santiago Metropolitan", country: "Chile", countryCode: "CL", type: "city" },
  { value: "Valparaíso,Valparaíso,CL", label: "Valparaíso, Chile", city: "Valparaíso", state: "Valparaíso", country: "Chile", countryCode: "CL", type: "city" },
  { value: "CL", label: "Chile", country: "Chile", countryCode: "CL", type: "country" },

  // Country-only options
  { value: "US", label: "United States", country: "United States", countryCode: "US", type: "country" },
  { value: "CA", label: "Canada", country: "Canada", countryCode: "CA", type: "country" },
  { value: "MX", label: "Mexico", country: "Mexico", countryCode: "MX", type: "country" },
]
