import { useState, useEffect } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabaseClient'
import { useAuth } from '@/contexts/AuthContext'
import { toast } from 'sonner'

export interface CareersPageSettings {
  id: string
  tenant_id: string
  logo_url: string | null
  company_website_url: string | null
  company_slug: string
  page_title: string
  header_text: string | null
  show_company_name: boolean
  is_active: boolean
  created_at: string
  updated_at: string
}

export function useCareersPageSettings() {
  const { user, organizationId } = useAuth()
  const queryClient = useQueryClient()

  // Get tenant ID from organization
  const [tenantId, setTenantId] = useState<string | null>(null)

  // Fetch tenant ID when organization changes
  useEffect(() => {
    const fetchTenantId = async () => {
      if (!organizationId) {
        setTenantId(null)
        return
      }

      const { data, error } = await supabase
        .from('organizations')
        .select('tenant_id')
        .eq('id', organizationId)
        .single()

      if (!error && data) {
        setTenantId(data.tenant_id)
      }
    }

    fetchTenantId()
  }, [organizationId])

  // Fetch settings
  const { data: settings, isLoading, error } = useQuery({
    queryKey: ['careers-page-settings', tenantId],
    queryFn: async () => {
      if (!tenantId) return null

      const { data, error } = await supabase
        .from('careers_page_settings')
        .select('*')
        .eq('tenant_id', tenantId)
        .single()

      if (error && error.code !== 'PGRST116') {
        throw error
      }

      return data as CareersPageSettings | null
    },
    enabled: !!tenantId,
  })

  // Initialize settings if they don't exist
  const initializeMutation = useMutation({
    mutationFn: async () => {
      if (!tenantId || !user) throw new Error('No tenant or user')

      const { data, error } = await supabase
        .from('careers_page_settings')
        .insert({
          tenant_id: tenantId,
          company_slug: '', // Will be auto-generated by trigger
          created_by: user.id,
        })
        .select()
        .single()

      if (error) throw error
      return data as CareersPageSettings
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['careers-page-settings', tenantId] })
      toast.success('Careers page initialized')
    },
    onError: (error: Error) => {
      console.error('Failed to initialize careers page:', error)
      toast.error('Failed to initialize careers page')
    },
  })

  // Update settings
  const updateMutation = useMutation({
    mutationFn: async (updates: Partial<CareersPageSettings>) => {
      if (!tenantId) throw new Error('No tenant')

      const { data, error } = await supabase
        .from('careers_page_settings')
        .update(updates)
        .eq('tenant_id', tenantId)
        .select()
        .single()

      if (error) throw error
      return data as CareersPageSettings
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['careers-page-settings', tenantId] })
      toast.success('Careers page updated')
    },
    onError: (error: Error) => {
      console.error('Failed to update careers page:', error)
      toast.error('Failed to update careers page')
    },
  })

  // Upload logo
  const uploadLogoMutation = useMutation({
    mutationFn: async (file: File) => {
      if (!tenantId) throw new Error('No tenant')

      const formData = new FormData()
      formData.append('file', file)
      formData.append('tenantId', tenantId)

      const { data, error } = await supabase.functions.invoke('upload-careers-logo', {
        body: formData,
      })

      if (error) throw error
      return data
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['careers-page-settings', tenantId] })
      toast.success('Logo uploaded successfully')
    },
    onError: (error: Error) => {
      console.error('Failed to upload logo:', error)
      toast.error('Failed to upload logo')
    },
  })

  // Check slug availability
  const checkSlugAvailability = async (slug: string): Promise<boolean> => {
    if (!tenantId) return false

    const { data, error } = await supabase
      .from('careers_page_settings')
      .select('id')
      .eq('company_slug', slug)
      .neq('tenant_id', tenantId)
      .maybeSingle()

    if (error) {
      console.error('Error checking slug:', error)
      return false
    }

    return !data
  }

  return {
    settings,
    isLoading,
    error,
    initializeSettings: initializeMutation.mutate,
    isInitializing: initializeMutation.isPending,
    updateSettings: updateMutation.mutate,
    isUpdating: updateMutation.isPending,
    uploadLogo: uploadLogoMutation.mutate,
    isUploadingLogo: uploadLogoMutation.isPending,
    checkSlugAvailability,
  }
}
