import { useState, useMemo, useCallback, useEffect } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Search, Copy, RefreshCw, Edit2, X } from 'lucide-react';
import { useExternalSourcing, SourcingQuery } from '@/hooks/useExternalSourcing';
import { useOrgContext } from '@/contexts/OrgContext';
import { canRunExternalSearch } from '@/utils/sourcingCredits';
import { useOrgCredits } from '@/hooks/useOrgCredits';
import { CandidateTable } from '@/components/candidates/CandidateTable';
import { CandidatePreviewSlider } from '@/components/candidates/CandidatePreviewSlider';
import { toast } from '@/hooks/use-toast';
import { Skeleton } from '@/components/ui/skeleton';
import { supabase } from '@/integrations/supabase/client';
import { buildDefaultBoolean } from '@/lib/booleanQuery';

interface SourcingTabProps {
  jobId: string;
}

export function SourcingTab({ jobId }: SourcingTabProps) {
  const { organizationId } = useOrgContext();
  const { credits, refetch: refetchCredits } = useOrgCredits();
  const { results, total, isLoading, error, creditsInfo, runSearch, reset } = useExternalSourcing();

  // Filter state
  const [locations, setLocations] = useState<string>('');
  const [seniority, setSeniority] = useState<string>('');
  const [languages, setLanguages] = useState<string>('');
  const [updatedWithin, setUpdatedWithin] = useState<string>('');
  const [excludeInPipeline, setExcludeInPipeline] = useState(false);
  const [booleanQuery, setBooleanQuery] = useState('');
  const [isBooleanEditing, setIsBooleanEditing] = useState(false);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  
  // Pagination
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 25;

  // Preview state
  const [previewCandidate, setPreviewCandidate] = useState<any>(null);
  const [previewOpen, setPreviewOpen] = useState(false);

  // Live region for accessibility
  const [announcement, setAnnouncement] = useState('');

  useEffect(() => {
    if (!error) {
      return;
    }

    toast({
      title: 'External search failed',
      description: error,
      variant: 'destructive',
    });
  }, [error]);

  // Check if search can run
  const effectiveBoolean = useMemo(() => {
    if (booleanQuery.trim()) return booleanQuery.trim();
    // Fallback: we could try to build default here, but for now just check emptiness
    return '';
  }, [booleanQuery]);

  const canSearch = useMemo(() => {
    const hasCredits = (credits?.search.remaining ?? 0) > 0;
    const hasValidQuery = !!effectiveBoolean && effectiveBoolean.length > 0;
    return hasCredits && hasValidQuery && !isLoading;
  }, [credits, effectiveBoolean, isLoading]);

  // Auto-populate boolean query on mount
  useEffect(() => {
    if (!jobId || booleanQuery) return;

    const fetchJobAndGenerateBoolean = async () => {
      const { data: job, error } = await supabase
        .from('jobs')
        .select('title, standardized_skills, location')
        .eq('id', jobId)
        .single();

      if (error || !job) return;

      const autoQuery = buildDefaultBoolean({
        title: job.title,
        skills: job.standardized_skills || [],
        location: job.location || undefined,
      });

      if (autoQuery) {
        setBooleanQuery(autoQuery);
        setIsAutoGenerated(true);
      }
    };

    fetchJobAndGenerateBoolean();
  }, [jobId, booleanQuery]);

  // Build query from filters
  const buildQuery = useCallback((): SourcingQuery => {
    const query: SourcingQuery = {};

    // Always include boolean query
    if (booleanQuery.trim()) {
      query.boolean = booleanQuery.trim();
    }

    if (locations.trim()) {
      query.locations = locations.split(',').map(l => l.trim()).filter(Boolean);
    }

    if (seniority && seniority !== 'all') {
      query.seniority = [seniority];
    }

    if (languages.trim()) {
      query.languages = languages.split(',').map(l => l.trim()).filter(Boolean);
    }

    if (updatedWithin && updatedWithin !== 'any') {
      const daysMap: Record<string, number> = {
        '30d': 30,
        '6mo': 180,
        '12mo': 365,
      };
      const days = daysMap[updatedWithin];
      if (days !== undefined) {
        query.updated_within_days = days;
      }
    }

    return query;
  }, [booleanQuery, locations, seniority, languages, updatedWithin]);

  // Handle search execution
  const handleRunSearch = useCallback(async () => {
    if (!organizationId) {
      toast({
        title: 'Error',
        description: 'No organization selected',
        variant: 'destructive',
      });
      return;
    }

    if (!canSearch) {
      toast({
        title: 'Cannot Search',
        description: 'Ensure you have credits and a valid boolean query',
        variant: 'destructive',
      });
      return;
    }

    const query = buildQuery();
    
    await runSearch({
      organization_id: organizationId,
      job_id: jobId,
      query,
      pagination: {
        page: currentPage,
        pageSize,
      },
    });

    // Refetch credits if charged
    if (creditsInfo && creditsInfo.charged > 0) {
      refetchCredits();
    }

    // Update announcement
    setAnnouncement(`Search completed. Found ${total} candidates.`);
  }, [organizationId, jobId, currentPage, canSearch, buildQuery, runSearch, creditsInfo, total, refetchCredits]);

  // Reset filters
  const handleReset = useCallback(() => {
    setLocations('');
    setSeniority('');
    setLanguages('');
    setUpdatedWithin('');
    setExcludeInPipeline(false);
    setBooleanQuery('');
    setIsBooleanEditing(false);
    reset();
    setCurrentPage(1);
    setAnnouncement('Filters reset');
  }, [reset]);

  // Copy boolean query
  const handleCopyBoolean = useCallback(() => {
    if (booleanQuery) {
      navigator.clipboard.writeText(booleanQuery);
      toast({
        title: 'Copied',
        description: 'Boolean query copied to clipboard',
      });
    }
  }, [booleanQuery]);

  // Regenerate boolean (placeholder)
  const handleRegenerateBoolean = useCallback(() => {
    // TODO: Implement AI-powered boolean generation in future
    toast({
      title: 'Coming Soon',
      description: 'AI-powered boolean generation will be available soon',
    });
  }, []);

  // Map results to CandidateTable format
  const mappedCandidates = useMemo(() => {
    return results.map(result => ({
      id: result.provider_ref,
      candidate_name: result.name || 'Unknown',
      location_country: result.location || null,
      location_state: null,
      location_city: null,
      salary_amount: null,
      salary_currency: null,
      salary_period: null,
      profile_summary: null,
      skills: null,
      created_at: result.lastUpdatedAt || new Date().toISOString(),
      first_viewed_by: null,
      match_score: result.match,
      match_tier: result.match >= 80 ? 'excellent' as const : 
                  result.match >= 60 ? 'good' as const : 
                  result.match >= 40 ? 'fair' as const : 'minimal' as const,
      job_id: jobId,
      notes: null,
      added_by: null,
      updated_at: result.lastUpdatedAt || new Date().toISOString(),
      _sourcingData: result, // Store full result for preview
    }));
  }, [results, jobId]);

  // Handle row click
  const handleRowClick = useCallback((candidateId: string) => {
    const candidate = mappedCandidates.find(c => c.id === candidateId);
    if (candidate && (candidate as any)._sourcingData) {
      setPreviewCandidate((candidate as any)._sourcingData);
      setPreviewOpen(true);
    }
  }, [mappedCandidates]);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // "/" to focus boolean
      if (e.key === '/' && !isBooleanEditing) {
        e.preventDefault();
        setIsBooleanEditing(true);
      }
      // "R" to run search
      if (e.key === 'r' && !isBooleanEditing && canSearch) {
        e.preventDefault();
        handleRunSearch();
      }
      // "Esc" to close preview
      if (e.key === 'Escape' && previewOpen) {
        setPreviewOpen(false);
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isBooleanEditing, canSearch, handleRunSearch, previewOpen]);

  return (
    <div className="flex gap-4 h-full">
      {/* Left Filter Column */}
      <div className="w-[280px] flex-shrink-0">
        <Card className="h-full flex flex-col">
          <CardContent className="pt-6 flex-1 overflow-y-auto space-y-4">
            {/* Location */}
            <div className="space-y-2">
              <Label htmlFor="locations">Locations</Label>
              <Input
                id="locations"
                placeholder="e.g., San Francisco, Remote"
                value={locations}
                onChange={(e) => setLocations(e.target.value)}
              />
              <p className="text-xs text-muted-foreground">Comma-separated</p>
            </div>

            {/* Seniority */}
            <div className="space-y-2">
              <Label htmlFor="seniority">Seniority</Label>
              <Select value={seniority} onValueChange={setSeniority}>
                <SelectTrigger id="seniority">
                  <SelectValue placeholder="Any" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">Any</SelectItem>
                  <SelectItem value="junior">Junior</SelectItem>
                  <SelectItem value="mid">Mid</SelectItem>
                  <SelectItem value="senior">Senior</SelectItem>
                  <SelectItem value="lead">Lead</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Languages */}
            <div className="space-y-2">
              <Label htmlFor="languages">Languages</Label>
              <Input
                id="languages"
                placeholder="e.g., English, Spanish"
                value={languages}
                onChange={(e) => setLanguages(e.target.value)}
              />
              <p className="text-xs text-muted-foreground">Comma-separated</p>
            </div>

            {/* Updated Within */}
            <div className="space-y-2">
              <Label htmlFor="updated">Updated Within</Label>
              <Select value={updatedWithin} onValueChange={setUpdatedWithin}>
                <SelectTrigger id="updated">
                  <SelectValue placeholder="Any" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="any">Any</SelectItem>
                  <SelectItem value="30d">≤ 30 days</SelectItem>
                  <SelectItem value="6mo">≤ 6 months</SelectItem>
                  <SelectItem value="12mo">≤ 12 months</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Exclude in Pipeline */}
            <div className="flex items-center space-x-2">
              <Checkbox
                id="exclude"
                checked={excludeInPipeline}
                onCheckedChange={(checked) => setExcludeInPipeline(!!checked)}
              />
              <Label htmlFor="exclude" className="text-sm cursor-pointer">
                Exclude already in pipeline
              </Label>
            </div>
          </CardContent>

          {/* Sticky Footer */}
          <div className="p-4 border-t space-y-2">
            <Button
              onClick={handleRunSearch}
              disabled={!canSearch}
              className="w-full"
            >
              <Search className="h-4 w-4 mr-2" />
              {isLoading ? 'Searching...' : 'Run External Search'}
            </Button>
            <Button onClick={handleReset} variant="outline" className="w-full">
              Reset
            </Button>
          </div>
        </Card>
      </div>

      {/* Center Results */}
      <div className="flex-1 flex flex-col gap-4">
        {/* Boolean Query Strip */}
        <Card>
          <CardContent className="pt-4">
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label htmlFor="boolean">Boolean Query</Label>
                <div className="flex gap-2">
                  {!isBooleanEditing && booleanQuery && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={handleCopyBoolean}
                      title="Copy boolean query"
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                  )}
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={handleRegenerateBoolean}
                    title="Regenerate boolean query"
                  >
                    <RefreshCw className="h-4 w-4" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setIsBooleanEditing(!isBooleanEditing)}
                    title={isBooleanEditing ? 'Close editor' : 'Edit boolean query'}
                  >
                    {isBooleanEditing ? <X className="h-4 w-4" /> : <Edit2 className="h-4 w-4" />}
                  </Button>
                </div>
              </div>
              {isBooleanEditing ? (
                <div className="space-y-2">
                  <Textarea
                    id="boolean"
                    placeholder="Enter boolean search query (optional)"
                    value={booleanQuery}
                    onChange={(e) => {
                      setBooleanQuery(e.target.value);
                      setIsAutoGenerated(false);
                    }}
                    rows={3}
                  />
                  {isAutoGenerated && (
                    <p className="text-xs text-muted-foreground">
                      Generated from job spec — edit as needed.
                    </p>
                  )}
                </div>
              ) : (
                <div className="space-y-1">
                  <div className="text-sm text-muted-foreground min-h-[60px] flex items-center">
                    {booleanQuery || 'No boolean query set'}
                  </div>
                  {isAutoGenerated && (
                    <p className="text-xs text-muted-foreground">
                      Generated from job spec — edit as needed.
                    </p>
                  )}
                </div>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Results Table */}
        <Card className="flex-1 overflow-hidden flex flex-col">
          <CardContent className="pt-6 flex-1 overflow-auto">
            {error && (
              <div className="text-sm text-destructive mb-4 p-3 bg-destructive/10 rounded">
                {error}
              </div>
            )}
            
            {isLoading ? (
              <div className="space-y-2">
                {Array.from({ length: 5 }).map((_, i) => (
                  <Skeleton key={i} className="h-16 w-full" />
                ))}
              </div>
            ) : (
              <CandidateTable
                candidates={mappedCandidates}
                isLoading={false}
                onEdit={() => {}}
                onDelete={() => {}}
                markCandidateAsViewed={() => {}}
                isCandidateNewForUser={() => false}
                showMatchScore={true}
                hideActions={true}
                onRowClick={handleRowClick}
              />
            )}
          </CardContent>
        </Card>
      </div>

      {/* Preview Slider */}
      <CandidatePreviewSlider
        isOpen={previewOpen}
        onClose={() => setPreviewOpen(false)}
        candidate={previewCandidate}
      />

      {/* Live Region for Screen Readers */}
      <div
        role="status"
        aria-live="polite"
        aria-atomic="true"
        className="sr-only"
      >
        {announcement}
      </div>
    </div>
  );
}
