// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Virgilio user's id and email. Use to verify the MCP connection is authenticated.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail() ?? null,
      client_id: ctx.getClientId() ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-jobs.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_jobs_default = defineTool2({
  name: "list_jobs",
  title: "List jobs",
  description: "List jobs the signed-in user can see in Virgilio. Optionally filter by status (e.g. open, closed, draft). Returns up to `limit` rows.",
  inputSchema: {
    status: z.string().trim().min(1).nullable().describe("Optional job status filter (e.g. 'open')."),
    limit: z.number().int().min(1).max(50).nullable().describe("Max rows to return (1-50). Defaults to 20.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("jobs").select("id, title, status, department, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-candidates.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_candidates_default = defineTool3({
  name: "search_candidates",
  title: "Search candidates",
  description: "Search candidates by name or email substring in Virgilio. Returns up to `limit` matches the signed-in user can access.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Substring to match against first name, last name, or email."),
    limit: z2.number().int().min(1).max(50).nullable().describe("Max rows to return (1-50). Defaults to 20.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const like = `%${query.replace(/[%_]/g, "")}%`;
    const { data, error } = await supabase.from("candidates").select("id, first_name, last_name, email, current_title, current_company, created_at").or(
      `first_name.ilike.${like},last_name.ilike.${like},email.ilike.${like}`
    ).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { candidates: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-candidate.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_candidate_default = defineTool4({
  name: "get_candidate",
  title: "Get candidate",
  description: "Fetch the full profile of a Virgilio candidate by id, subject to the signed-in user's access.",
  inputSchema: {
    candidate_id: z3.string().uuid().describe("The candidate's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ candidate_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("candidates").select("*").eq("id", candidate_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Candidate not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { candidate: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "etrxjxstjfcozdjumfsj";
var mcp_default = defineMcp({
  name: "virgilio-mcp",
  title: "Virgilio",
  version: "0.1.0",
  instructions: "Tools for Virgilio, an ATS/CRM. Use `whoami` to verify the connection, `list_jobs` to browse open roles, `search_candidates` to find people by name or email, and `get_candidate` for a full profile. All calls run as the signed-in Virgilio user and respect their permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_jobs_default, search_candidates_default, get_candidate_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
