-- Fix duplicate_job_posting to correctly reference new field IDs when copying options
CREATE OR REPLACE FUNCTION public.duplicate_job_posting(
  source_posting_id uuid,
  new_title text DEFAULT NULL,
  new_description text DEFAULT NULL,
  new_details jsonb DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_job_id uuid;
  v_new_posting_id uuid;
BEGIN
  -- Permission check: platform admin, org recruiter/admin, or assigned to job
  SELECT jp.job_id INTO v_job_id
  FROM public.job_postings jp
  WHERE jp.id = source_posting_id;

  IF v_job_id IS NULL THEN
    RAISE EXCEPTION 'Source posting not found';
  END IF;

  IF public.get_user_type_secure() <> 'platform_admin' THEN
    IF NOT EXISTS (
      SELECT 1
      FROM public.jobs j
      JOIN public.members m ON m.organization_id = j.organization_id
      WHERE j.id = v_job_id
        AND m.user_id = auth.uid()
        AND m.user_status = 'active'
        AND m.member_role IN ('admin','recruiter')
    ) AND NOT EXISTS (
      SELECT 1 FROM public.job_assignments ja
      WHERE ja.job_id = v_job_id AND ja.user_id = auth.uid()
    ) THEN
      RAISE EXCEPTION 'Insufficient permissions to duplicate posting';
    END IF;
  END IF;

  -- Create new posting; slug generated by trigger; defaults will seed fields which we'll replace
  INSERT INTO public.job_postings (job_id, title, description, details, is_active, created_by)
  SELECT 
    jp.job_id,
    COALESCE(new_title, jp.title || ' (Copy)'),
    COALESCE(new_description, jp.description),
    COALESCE(new_details, jp.details),
    false,
    auth.uid()
  FROM public.job_postings jp
  WHERE jp.id = source_posting_id
  RETURNING id INTO v_new_posting_id;

  -- Remove any default-seeded fields to ensure exact mirroring
  DELETE FROM public.job_posting_application_fields WHERE posting_id = v_new_posting_id;

  -- Copy fields exact
  INSERT INTO public.job_posting_application_fields (
    posting_id,
    source,
    application_field_id,
    field_name,
    field_label,
    field_type,
    is_required,
    display_order,
    placeholder_text,
    help_text,
    accepted_file_types,
    max_file_size_mb,
    column_span
  )
  SELECT 
    v_new_posting_id,
    s.source,
    s.application_field_id,
    s.field_name,
    s.field_label,
    s.field_type,
    s.is_required,
    s.display_order,
    s.placeholder_text,
    s.help_text,
    s.accepted_file_types,
    s.max_file_size_mb,
    s.column_span
  FROM public.job_posting_application_fields s
  WHERE s.posting_id = source_posting_id;

  -- Copy select options by matching new field rows on display_order
  INSERT INTO public.posting_field_select_options (posting_field_id, option_label, option_value, display_order)
  SELECT n.id AS posting_field_id, o.option_label, o.option_value, o.display_order
  FROM public.posting_field_select_options o
  JOIN public.job_posting_application_fields s ON s.id = o.posting_field_id
  JOIN public.job_posting_application_fields n 
    ON n.posting_id = v_new_posting_id 
   AND n.display_order = s.display_order
  WHERE s.posting_id = source_posting_id;

  RETURN v_new_posting_id;
END;
$$;