-- Ensure default full-width fields on new postings
ALTER TABLE public.job_posting_application_fields
ALTER COLUMN column_span SET DEFAULT 4;

-- Update trigger function to seed defaults as full-width
CREATE OR REPLACE FUNCTION public.add_default_application_fields_to_posting()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  rn int := 0;
  r record;
BEGIN
  FOR r IN
    SELECT 
      af.id as application_field_id,
      af.field_name,
      af.field_label,
      af.field_type,
      af.placeholder_text,
      af.help_text,
      af.accepted_file_types,
      af.max_file_size_mb
    FROM public.application_fields af
    WHERE af.is_default = true
    ORDER BY af.display_order, af.created_at
  LOOP
    rn := rn + 1;
    INSERT INTO public.job_posting_application_fields (
      posting_id,
      source,
      application_field_id,
      field_name,
      field_label,
      field_type,
      is_required,
      display_order,
      placeholder_text,
      help_text,
      accepted_file_types,
      max_file_size_mb,
      column_span
    ) VALUES (
      NEW.id,
      'library',
      r.application_field_id,
      r.field_name,
      r.field_label,
      r.field_type,
      false,
      rn,
      r.placeholder_text,
      r.help_text,
      r.accepted_file_types,
      r.max_file_size_mb,
      4  -- full width by default
    );
  END LOOP;
  RETURN NEW;
END;
$$;

-- Function to duplicate a job posting with its fields and options
CREATE OR REPLACE FUNCTION public.duplicate_job_posting(
  source_posting_id uuid,
  new_title text DEFAULT NULL,
  new_description text DEFAULT NULL,
  new_details jsonb DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_job_id uuid;
  v_new_posting_id uuid;
BEGIN
  -- Permission check: platform admin, org recruiter/admin, or assigned to job
  SELECT jp.job_id INTO v_job_id
  FROM public.job_postings jp
  WHERE jp.id = source_posting_id;

  IF v_job_id IS NULL THEN
    RAISE EXCEPTION 'Source posting not found';
  END IF;

  IF public.get_user_type_secure() <> 'platform_admin' THEN
    IF NOT EXISTS (
      SELECT 1
      FROM public.jobs j
      JOIN public.members m ON m.organization_id = j.organization_id
      WHERE j.id = v_job_id
        AND m.user_id = auth.uid()
        AND m.user_status = 'active'
        AND m.member_role IN ('admin','recruiter')
    ) AND NOT EXISTS (
      SELECT 1 FROM public.job_assignments ja
      WHERE ja.job_id = v_job_id AND ja.user_id = auth.uid()
    ) THEN
      RAISE EXCEPTION 'Insufficient permissions to duplicate posting';
    END IF;
  END IF;

  -- Create new posting; slug generated by trigger; defaults will seed fields which we'll replace
  INSERT INTO public.job_postings (job_id, title, description, details, is_active, created_by)
  SELECT 
    jp.job_id,
    COALESCE(new_title, jp.title || ' (Copy)'),
    COALESCE(new_description, jp.description),
    COALESCE(new_details, jp.details),
    false,
    auth.uid()
  FROM public.job_postings jp
  WHERE jp.id = source_posting_id
  RETURNING id INTO v_new_posting_id;

  -- Remove any default-seeded fields to ensure exact mirroring
  DELETE FROM public.job_posting_application_fields WHERE posting_id = v_new_posting_id;

  -- Map old fields to new fields and copy them
  WITH src AS (
    SELECT * FROM public.job_posting_application_fields WHERE posting_id = source_posting_id
  ), ins AS (
    INSERT INTO public.job_posting_application_fields (
      posting_id,
      source,
      application_field_id,
      field_name,
      field_label,
      field_type,
      is_required,
      display_order,
      placeholder_text,
      help_text,
      accepted_file_types,
      max_file_size_mb,
      column_span
    )
    SELECT 
      v_new_posting_id,
      s.source,
      s.application_field_id,
      s.field_name,
      s.field_label,
      s.field_type,
      s.is_required,
      s.display_order,
      s.placeholder_text,
      s.help_text,
      s.accepted_file_types,
      s.max_file_size_mb,
      s.column_span
    FROM src s
    RETURNING id AS new_field_id
           ,field_name
           ,display_order
           ,application_field_id
  )
  -- Copy select options by matching on the original order via application_field_id + display_order
  INSERT INTO public.posting_field_select_options (posting_field_id, option_label, option_value, display_order)
  SELECT n.new_field_id, o.option_label, o.option_value, o.display_order
  FROM public.posting_field_select_options o
  JOIN public.job_posting_application_fields s ON s.id = o.posting_field_id
  JOIN public.job_posting_application_fields n ON n.posting_id = v_new_posting_id AND n.display_order = s.display_order
  WHERE s.posting_id = source_posting_id;

  RETURN v_new_posting_id;
END;
$$;